### ISSUE TITLE
How to copy to bucket on another account?

### ISSUE THREAD

**Issue by AJB99** [eleven41/aws-lambda-copy-s3-objects#4]
Hi there,

Any idea how this could be used to copy an object to a bucket under another account?

I've attempted something similar, but keep getting `Access Denied` no matter that `IAM/Bucket Policy` configuration I use.

You can see an SO thread I've posted here:
http://stackoverflow.com/questions/40187728/how-to-use-aws-lambda-to-backup-an-s3-object-to-a-bucket-on-another-account

**Comment by mwhouser** [comment]
Hello,

It looks like we've solved your issue in the SO thread.

**Comment by AJB99** [comment]
Ha. I didn't even realize the connection until now. Indeed you did solve this. Thanks again, Matt.
